dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: test
      name: Apply Terraform test configs in mockstack
      install:
        - make docker-compose/install
        - make mockstack/up
      script: make mockstack/pytest
      after_script:
        - make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-iam-identity-provider
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-iam-identity-provider v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-iam-identity-provider/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: Wj2jwNj3NlI0Pn3bYTIklC5iat1bXKJFnPjX4s/aNlfmXMK6Zya2fDkTE4W3SCFjT1n8DhHhKa+C584LgUYB2vcJTa+Hq5biFOu+0/dOh6wEy2E0oKRFIYEfWUksGZkH8Cm4FFpg3mRg9lYGr7ycjX/y3xpaKicA365O/7FD2pDlWV01glOq43D7jKYgml6dy+BDcqnbdtxst7VhgtyGUNSTZiUUIP3b7V31oj32wNrELKXuQJtilhR9+MprLO2wGtg6CQzsGy/MoLTNnJmcNzYx44ldHNwgzqwvTwkgS3FnvXeSmDvMr0JmKqqnoFUd893xBTjl9tmNd9r8yTIfAw9JGZMzi4c4MHeXvEXO4/FbQKf00uatkaMc+kQKZtXCj2UI+pUT6l0p2VZqUsHuAfBRYGyf9vBagEFEy+BkSy53TENJtwz7Ki+WuDAHLqTTIwkVXpjDt5ohxLVe3QLRzQABXIrSqsHoOFc6lDHBV/u7+g4BfA1TZu57HYlG8ilaVov9gJK8fnbJ+156YbSrSEgEjG4Nqu3YMdc4Qjb0N1WpoqVIpVdfwEJ7JMAbOYhe0LyOWZIbz6xfjEFxh8wSf2xenOPYU+ON9qHwep+FlZLPK07/kyQxUf0HP8v3Rl/SIrRTV1GbRlRMgwxYiJCUGI4IZI45unksb4umSANp12U=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-iam-identity-provider
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
